import { AggregatedPlayerDashboard, SharedMatchItem } from '@/types/dashboard';
import { PLAYER_1, PLAYER_2 } from '@/lib/constants';

export const MOCK_SHARED_MATCHES: SharedMatchItem[] = [
  {
    id: 'demo-match-1',
    date: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    formattedDate: 'Hoje, 20:30',
    mapName: 'DFH Stadium',
    result: 'win',
    teamGoals: 4,
    opponentGoals: 2,
    sameTeam: true,
    isOvertime: false,
    durationSeconds: 300,
    p1Goals: 3,
    p1Assists: 1,
    p1Saves: 1,
    p1Score: 540,
    p1Bpm: 380,
    p2Goals: 1,
    p2Assists: 2,
    p2Saves: 3,
    p2Score: 480,
    p2Bpm: 360,
  },
  {
    id: 'demo-match-2',
    date: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
    formattedDate: 'Hoje, 19:45',
    mapName: 'Mannfield',
    result: 'win',
    teamGoals: 3,
    opponentGoals: 1,
    sameTeam: true,
    isOvertime: false,
    durationSeconds: 300,
    p1Goals: 2,
    p1Assists: 0,
    p1Saves: 2,
    p1Score: 460,
    p1Bpm: 360,
    p2Goals: 1,
    p2Assists: 1,
    p2Saves: 2,
    p2Score: 390,
    p2Bpm: 370,
  },
];

export const MOCK_LEOK07: AggregatedPlayerDashboard = {
  playerName: PLAYER_1.name,
  platform: PLAYER_1.platform,
  platformId: PLAYER_1.platformId,
  replaysAnalyzed: 2,
  session: {
    totalMatches: 2,
    wins: 2,
    losses: 0,
    winRate: 100,
    totalGoals: 5,
    goalsPerMatch: 2.5,
    totalAssists: 1,
    assistsPerMatch: 0.5,
    totalSaves: 3,
    savesPerMatch: 1.5,
    totalShots: 8,
    shotsPerMatch: 4.0,
    shootingPercentage: 62.5,
    avgScore: 500,
    mvpCount: 2,
    avgDurationSeconds: 300,
    overtimeCount: 0,
  },
  positioning: {
    avgDefensiveThird: 32.0,
    avgNeutralThird: 30.0,
    avgOffensiveThird: 38.0,
    avgDefensiveHalf: 45.0,
    avgOffensiveHalf: 55.0,
    avgBehindBall: 60.0,
    avgInfrontBall: 40.0,
    avgDistanceToTeammate: 3100,
    avgDistanceToBall: 2200,
    avgMostBack: 36.0,
    avgMostForward: 44.0,
  },
  boost: {
    avgBpm: 370,
    avgBcpm: 390,
    avgAmount: 52.0,
    avgStolenBig: 1.5,
    avgStolenSmall: 4.0,
    totalStolenBig: 3,
    avgCollectedBig: 4.5,
    avgCollectedSmall: 14.0,
    avgSupersonicWaste: 8.0,
    avgZeroBoostPercent: 5.0,
    avgFullBoostPercent: 12.0,
    avgOverfill: 15.0,
    boostDistribution: { range0_25: 22, range25_50: 30, range50_75: 28, range75_100: 20 },
  },
  movement: {
    avgSpeed: 1450,
    avgSpeedPercentage: 65.0,
    avgSupersonicPercent: 14.0,
    avgBoostSpeedPercent: 34.0,
    avgSlowSpeedPercent: 16.0,
    avgGroundPercent: 68.0,
    avgLowAirPercent: 24.0,
    avgHighAirPercent: 8.0,
    avgPowerslideCount: 56,
    avgPowerslideDuration: 0.18,
    totalDistance: 125000,
  },
  demos: { totalInflicted: 2, totalTaken: 1, avgInflicted: 1.0, avgTaken: 0.5, demoRatio: 2.0 },
  radar: [
    { axis: 'Agressividade', value: 88, fullMark: 100 },
    { axis: 'Contencao Defensiva', value: 72, fullMark: 100 },
    { axis: 'Eficiencia Mecanica', value: 84, fullMark: 100 },
    { axis: 'Suporte e Posicionamento', value: 76, fullMark: 100 },
    { axis: 'Controle de Boost', value: 80, fullMark: 100 },
  ],
  futStats: {
    ovr: 88,
    tier: 'hero',
    position: 'ATA',
    positionLabel: 'Ataque',
    pac: 85,
    sho: 90,
    pas: 78,
    dri: 84,
    def: 72,
    phy: 65,
    streakCount: 2,
    streakType: 'win',
    recentWinRate: 100,
    recentMatchesCount: 2,
    nickname: 'Artilheiro Implacável',
    nicknameCategory: 'Artilharia',
    isNegativeNickname: false,
    recentGoals: 5,
    recentAssists: 1,
    recentSaves: 3,
    recentShots: 8,
    recentMvps: 2,
    recentMvpStreak: 2,
    recentAvgScore: 500,
  },
  matchHistory: [
    {
      id: 'demo-match-1',
      date: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
      mapName: 'DFH Stadium',
      result: 'win',
      scoreTeam: 4,
      scoreOpponent: 2,
      duration: 300,
      isOvertime: false,
      goals: 3,
      assists: 1,
      saves: 1,
      shots: 5,
      score: 540,
      bpm: 380,
      supersonicPercent: 15,
      demoInflicted: 1,
    },
    {
      id: 'demo-match-2',
      date: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
      mapName: 'Mannfield',
      result: 'win',
      scoreTeam: 3,
      scoreOpponent: 1,
      duration: 300,
      isOvertime: false,
      goals: 2,
      assists: 0,
      saves: 2,
      shots: 3,
      score: 460,
      bpm: 360,
      supersonicPercent: 13,
      demoInflicted: 1,
    },
  ],
  trendHistory: [],
  replays: [],
};

export const MOCK_THEUSZRIB: AggregatedPlayerDashboard = {
  playerName: PLAYER_2.name,
  platform: PLAYER_2.platform,
  platformId: PLAYER_2.platformId,
  replaysAnalyzed: 2,
  session: {
    totalMatches: 2,
    wins: 2,
    losses: 0,
    winRate: 100,
    totalGoals: 2,
    goalsPerMatch: 1.0,
    totalAssists: 3,
    assistsPerMatch: 1.5,
    totalSaves: 5,
    savesPerMatch: 2.5,
    totalShots: 5,
    shotsPerMatch: 2.5,
    shootingPercentage: 40.0,
    avgScore: 435,
    mvpCount: 0,
    avgDurationSeconds: 300,
    overtimeCount: 0,
  },
  positioning: {
    avgDefensiveThird: 48.0,
    avgNeutralThird: 28.0,
    avgOffensiveThird: 24.0,
    avgDefensiveHalf: 58.0,
    avgOffensiveHalf: 42.0,
    avgBehindBall: 72.0,
    avgInfrontBall: 28.0,
    avgDistanceToTeammate: 3250,
    avgDistanceToBall: 2450,
    avgMostBack: 54.0,
    avgMostForward: 32.0,
  },
  boost: {
    avgBpm: 365,
    avgBcpm: 380,
    avgAmount: 56.0,
    avgStolenBig: 2.0,
    avgStolenSmall: 5.0,
    totalStolenBig: 4,
    avgCollectedBig: 5.0,
    avgCollectedSmall: 16.0,
    avgSupersonicWaste: 6.0,
    avgZeroBoostPercent: 4.0,
    avgFullBoostPercent: 15.0,
    avgOverfill: 12.0,
    boostDistribution: { range0_25: 18, range25_50: 32, range50_75: 30, range75_100: 20 },
  },
  movement: {
    avgSpeed: 1480,
    avgSpeedPercentage: 67.0,
    avgSupersonicPercent: 16.0,
    avgBoostSpeedPercent: 36.0,
    avgSlowSpeedPercent: 14.0,
    avgGroundPercent: 66.0,
    avgLowAirPercent: 26.0,
    avgHighAirPercent: 8.0,
    avgPowerslideCount: 60,
    avgPowerslideDuration: 0.19,
    totalDistance: 128000,
  },
  demos: { totalInflicted: 3, totalTaken: 0, avgInflicted: 1.5, avgTaken: 0.0, demoRatio: 3.0 },
  radar: [
    { axis: 'Agressividade', value: 70, fullMark: 100 },
    { axis: 'Contencao Defensiva', value: 92, fullMark: 100 },
    { axis: 'Eficiencia Mecanica', value: 82, fullMark: 100 },
    { axis: 'Suporte e Posicionamento', value: 89, fullMark: 100 },
    { axis: 'Controle de Boost', value: 84, fullMark: 100 },
  ],
  futStats: {
    ovr: 89,
    tier: 'hero',
    position: 'DEF',
    positionLabel: 'Defensor',
    pac: 92,
    sho: 68,
    pas: 88,
    dri: 83,
    def: 91,
    phy: 82,
    streakCount: 2,
    streakType: 'win',
    recentWinRate: 100,
    recentMatchesCount: 2,
    nickname: 'Muralha Intransponível',
    nicknameCategory: 'Muralha Defensiva',
    isNegativeNickname: false,
    recentGoals: 2,
    recentAssists: 3,
    recentSaves: 5,
    recentShots: 5,
    recentMvps: 0,
    recentMvpStreak: 0,
    recentAvgScore: 435,
  },
  matchHistory: [
    {
      id: 'demo-match-1',
      date: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
      mapName: 'DFH Stadium',
      result: 'win',
      scoreTeam: 4,
      scoreOpponent: 2,
      duration: 300,
      isOvertime: false,
      goals: 1,
      assists: 2,
      saves: 3,
      shots: 3,
      score: 480,
      bpm: 360,
      supersonicPercent: 16,
      demoInflicted: 2,
    },
    {
      id: 'demo-match-2',
      date: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
      mapName: 'Mannfield',
      result: 'win',
      scoreTeam: 3,
      scoreOpponent: 1,
      duration: 300,
      isOvertime: false,
      goals: 1,
      assists: 1,
      saves: 2,
      shots: 2,
      score: 390,
      bpm: 370,
      supersonicPercent: 16,
      demoInflicted: 1,
    },
  ],
  trendHistory: [],
  replays: [],
};

export const MOCK_PLAYER_1 = MOCK_LEOK07;
export const MOCK_PLAYER_2 = MOCK_THEUSZRIB;
